### ISSUE TITLE
Deploy failed due to an error in @netlify/plugin-nextjs plugin

### ISSUE THREAD

**Issue by lborruto** [commercelayer/sanity-template-commercelayer#41]
Hello there, trying to deploy via Netlify and getting this weird issue:

```
8:59:48 PM: ────────────────────────────────────────────────────────────────
8:59:48 PM:   Plugin "@netlify/plugin-nextjs" failed                        
8:59:48 PM: ────────────────────────────────────────────────────────────────
8:59:48 PM: ​
8:59:48 PM:   Error message
8:59:48 PM:   Error: The directory "out" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.
8:59:48 PM:   Your publish directory is set to "out", but in most cases it should be ".next".
8:59:48 PM:   If you are using "next export" then you should set the environment variable NETLIFY_NEXT_PLUGIN_SKIP to "true".
8:59:48 PM: ​
8:59:48 PM:   Plugin details
8:59:48 PM:   Package:        @netlify/plugin-nextjs
8:59:48 PM:   Version:        4.2.7
8:59:48 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
8:59:48 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
8:59:48 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
8:59:48 PM: ​
8:59:48 PM:   Error location
8:59:48 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
8:59:48 PM:       at checkNextSiteHasBuilt (/node_modules/@netlify/plugin-nextjs/lib/helpers/verification.js:68:16)
8:59:48 PM:       at onBuild (/node_modules/@netlify/plugin-nextjs/lib/index.js:37:50)
```

**Comment by BolajiAyodeji** [comment]
Hi @lborruto, thanks for reaching out.

I think there's some change with the @netlify/plugin-nextjs plugin; I'll investigate and get back to you. For now, you can follow the suggestion and try changing your publish directory to `.next`.

**Comment by lborruto** [comment]
> Hi @lborruto, thanks for reaching out.
> 
> I think there's some change with the @netlify/plugin-nextjs plugin; I'll investigate and get back to you. For now, you can follow the suggestion and try changing your publish directory to `.next`.

Thanks for this!
Tried to change to `.next` or disable that plugin but nothing is working for now.
